### PR TITLE
Pass a -march flag for arm64 clang build

### PR DESCRIPTION
**Pull request by zanderso**
Clang build fails on the assembly files.

### CODE REVIEW

**Comment by mraleph** [comment]
@zanderso should we try this instead: 

https://codereview.chromium.org/1475393002/

```
asmflags += [ "-march=armv8-a+crypto" ]
```

**Comment by zanderso** [comment]
Hmm. I tried a flag similar to that, but it was ineffective. I'll try that variant tomorrow as well, and see how it goes.

**Comment by zanderso** [comment]
asmflags += [ "-march=armv8-a+crypto" ] works. Thanks!

**Review by rmacnak-google — APPROVED** [review]
lgtm

**Pull request merged**
